#!/bin/bash

function main() {

    USERNAME=yufi
    PASSWORD=901004az
    DBHOST=localhost
    DBPORT=5432
    DBNAME=me
    
    postgrest `postgres://${USERNAME}:${PASSWORD}@${DBHOST}:${DBPORT}/${DBNAME} -p 4000 -a ${USERNAME} -o 2000 -s public`
    
}

main
