# Profile.


# QQ
[[contacts]]
  name    = "QQ number"
  content = "344292172"
  path    = "./Image/qq.jpg"
  order   = 1
  href    = """
    tencent://message/?uin=344292172
  """


# GayHub
[[contacts]]
  name    = "Github"
  content = "Rabbit"
  path    = "./Image/github.jpg"
  order   = 2
  href    = """
    https://github.com/yuffiy
  """


# Hotmail
[[contacts]]
  name    = "Hotmail"
  content = "@yfhj1990"
  path    = "./Image/email.jpg"
  order   = 3
  href    = """
    mailTo://yfhj1990@hotmail.com
  """


# QQ Group
[[contacts]]
  name    = "QQ group"
  content = "Export Elm"
  path    = "./Image/elm.jpg"
  order   = 4
  href    = """
    tencent://groupwpa/?subcmd=all&param=7B2267726F757055696E223A3533373938313535372C2274696D655374616D70223A313436313536343938347D0A
  """


# Food
[[props]]
  name  = "food"
  value = [
    "爱吃肉，但不会胖",
    "会煮咖啡，喜欢蓝山",
    "烹饪技能 Max",
    "各种甜点"
  ]


# Music
[[props]]
  name  = "music"
  value = [
    "轻音乐",
    "女声和电子鼓",
    "偶尔电音，抖腿向"
  ]


# Character
[[props]]
  name  = "character"
  value = [
    "卖萌技能 Max",
    "会偶尔着急",
    "常常闹别扭"
  ]
