#%RAML 1.0
title: Me API
version: v1
description: My blog RESTful APIs.
baseUri: https://yufi.me/api/{version}
protocols: [ HTTP ]
mediaType: application/json
types:
  Post: !include types/post.raml

/post:
  get:
    responses:
      200:
        body:
          application/json:
            schema: Post[]
  /{postId}:
    get:
      responses:
        200:
          body:
            application/json:
              schema: Post  
